### ISSUE TITLE
"Missing uncompyle6 Python module, please check if it is installed."

### ISSUE THREAD

**Issue by ljharnish** [NVISO-BE/decompile-py2exe#3]
I've tried for hours to fix this but nothing works, even installing different python versions and installing, reinstalling, everything I can do basically.

![image_2022-03-29_210618](https://user-images.githubusercontent.com/76492103/160730686-57cec360-1290-4c50-8985-a49ac3907a89.png)

**Comment by DidierStevens** [comment]
Can you try with the compiled script? That should work:
https://github.com/NVISOsecurity/decompile-py2exe/blob/master/Binaries/decompile-py2exe.exe

**Comment by ljharnish** [comment]
> Can you try with the compiled script? That should work: https://github.com/NVISOsecurity/decompile-py2exe/blob/master/Binaries/decompile-py2exe.exe

That seems to have gotten me farther but now im stuck with this.

![image](https://user-images.githubusercontent.com/76492103/160827225-ab158dd6-6263-4cab-af4c-32f544f187e3.png)

**Comment by DidierStevens** [comment]
That means your executable was not compiled with py2exe.
Or that it has been tampered with to make it unrecognizable.

**Comment by ljharnish** [comment]
> That means your executable was not compiled with py2exe. Or that it has been tampered with to make it unrecognizable.

Alright, thanks for the help man.

**Comment by Hinkiii** [comment]
I'll say it can't decompile my py2exe file that I made a while ago

Dating back to 2/8/2021 I have an exe from py2exe without it
